name: riverpod_testbed
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+2
environment:
  sdk: ">=2.19.2 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  riverpod: ^2.3.0
  flutter_riverpod: ^2.3.0
  freezed_annotation: ^2.2.0
  cupertino_icons: ^1.0.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  build_runner: ^2.3.3
flutter:
 uses-material-design: true